/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyCalendar;

import com.github.lgooddatepicker.components.DateTimePicker;
import java.util.Date;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author shane
 */
public class EventShow extends javax.swing.JFrame {


    /**
     * Creates new form EventShow
     */
    public EventShow() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        sms = new javax.swing.JRadioButton();
        openDataLink = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        watchState = new javax.swing.JComboBox<>();
        timeBefore = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        popup = new javax.swing.JRadioButton();
        email = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        event_app = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        event_private = new javax.swing.JRadioButton();
        inviterShow = new javax.swing.JComboBox<>();
        allDay = new javax.swing.JCheckBox();
        locationLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        eventNote = new javax.swing.JTextArea();
        stateLabel = new javax.swing.JLabel();
        eventName = new javax.swing.JLabel();
        EndTime = new javax.swing.JLabel();
        StartTime = new javax.swing.JLabel();
        Location = new javax.swing.JLabel();

        setTitle("編輯事件視窗");

        sms.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        sms.setText("sms");

        openDataLink.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 20)); // NOI18N
        openDataLink.setText("附件上傳");

        jLabel10.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 20)); // NOI18N
        jLabel10.setText("可見狀態");

        watchState.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        watchState.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "default (預設)", "public (活動公開)", "private (只限參與)", "confidential (只限本人)" }));

        timeBefore.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        timeBefore.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10分鐘前", "30分鐘前", "1小時前", "6小時前", "1天前", "1禮拜前" }));

        jLabel11.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 20)); // NOI18N
        jLabel11.setText("提醒方式及時間");

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 20)); // NOI18N
        jLabel1.setText("活動名稱");

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 20)); // NOI18N
        jLabel2.setText("開始時間");

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 20)); // NOI18N
        jLabel4.setText("活動類型");

        popup.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        popup.setText("popup");

        email.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        email.setText("email");

        jLabel12.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 20)); // NOI18N
        jLabel12.setText("與會者(名單與狀態)");

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 20)); // NOI18N
        jLabel3.setText("結束時間");

        buttonGroup1.add(event_app);
        event_app.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        event_app.setText("共用/公司事件");

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 20)); // NOI18N
        jLabel6.setText("活動備註");

        buttonGroup1.add(event_private);
        event_private.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        event_private.setText("私人事件");

        inviterShow.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        inviterShow.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "尚未新增" }));

        allDay.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        allDay.setText("全天活動");
        allDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allDayActionPerformed(evt);
            }
        });

        locationLabel.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 20)); // NOI18N
        locationLabel.setText("活動地點");

        eventNote.setEditable(false);
        eventNote.setColumns(20);
        eventNote.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        eventNote.setRows(5);
        eventNote.setToolTipText("");
        jScrollPane1.setViewportView(eventNote);

        stateLabel.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        stateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        eventName.setFont(new java.awt.Font("標楷體", 0, 30)); // NOI18N
        eventName.setText("eventName");

        EndTime.setFont(new java.awt.Font("標楷體", 0, 24)); // NOI18N
        EndTime.setForeground(new java.awt.Color(204, 0, 102));
        EndTime.setText("eventName");

        StartTime.setFont(new java.awt.Font("標楷體", 0, 24)); // NOI18N
        StartTime.setForeground(new java.awt.Color(0, 153, 153));
        StartTime.setText("eventName");

        Location.setFont(new java.awt.Font("標楷體", 0, 24)); // NOI18N
        Location.setText("eventName");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(stateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(45, 45, 45))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(event_private)
                                        .addGap(18, 18, 18)
                                        .addComponent(event_app))
                                    .addComponent(eventName, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(26, 26, 26)
                                        .addComponent(inviterShow, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(27, 27, 27)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(StartTime, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                                            .addComponent(EndTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(36, 36, 36)
                                        .addComponent(allDay, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(watchState, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(locationLabel)
                                .addGap(18, 18, 18)
                                .addComponent(Location))
                            .addComponent(openDataLink)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(email)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(popup)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sms))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(timeBefore, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(124, 124, 124))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eventName)
                    .addComponent(jLabel1))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(event_private)
                    .addComponent(event_app))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(inviterShow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(StartTime)
                    .addComponent(allDay))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(EndTime))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(locationLabel)
                                    .addComponent(Location))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(stateLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(timeBefore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(email)
                            .addComponent(popup)
                            .addComponent(sms))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(watchState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 55, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(openDataLink)
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 906, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void allDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allDayActionPerformed

    public JLabel getEndTime() {
        return EndTime;
    }

    public JLabel getMyLocation() {
        return Location;
    }

    public JLabel getStartTime() {
        return StartTime;
    }

    public JLabel getEventName() {
        return eventName;
    }

    public JLabel getLocationLabel() {
        return locationLabel;
    }

    public JLabel getOpenDataLink() {
        return openDataLink;
    }

    
    public JPanel getPanel(){
        return jPanel1;
                
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventShow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventShow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventShow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventShow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EventShow().setVisible(true);
            }
        });
    }

    public void msgbox(String msg){
        JOptionPane.showMessageDialog(null,msg );
    }
    




    public JCheckBox getAllDay() {
        return allDay;
    }

    public ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }


    public JRadioButton getEmail() {
        return email;
    }

    public JTextArea getEventNote() {
        return eventNote;
    }

    public JRadioButton getEvent_app() {
        return event_app;
    }

    public JRadioButton getEvent_private() {
        return event_private;
    }



    public JComboBox<String> getInviterShow() {
        return inviterShow;
    }


    public JRadioButton getPopup() {
        return popup;
    }

    public JRadioButton getSms() {
        return sms;
    }

    public JComboBox<String> getTimeBefore() {
        return timeBefore;
    }

    public JComboBox<String> getWatchState() {
        return watchState;
    }

    public JLabel getStateLabel() {
        return stateLabel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EndTime;
    private javax.swing.JLabel Location;
    private javax.swing.JLabel StartTime;
    private javax.swing.JCheckBox allDay;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton email;
    private javax.swing.JLabel eventName;
    private javax.swing.JTextArea eventNote;
    private javax.swing.JRadioButton event_app;
    private javax.swing.JRadioButton event_private;
    private javax.swing.JComboBox<String> inviterShow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JLabel openDataLink;
    private javax.swing.JRadioButton popup;
    private javax.swing.JRadioButton sms;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JComboBox<String> timeBefore;
    private javax.swing.JComboBox<String> watchState;
    // End of variables declaration//GEN-END:variables
}
