/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyCalendar;

import com.github.lgooddatepicker.components.DateTimePicker;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author shane
 */
public class EventEditShow extends javax.swing.JFrame {

 
    /**
     * Creates new form EventShow
     */
    public EventEditShow() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        sms = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        openFile = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        EndDateTimePicker = new com.github.lgooddatepicker.components.DateTimePicker();
        jLabel10 = new javax.swing.JLabel();
        watchState = new javax.swing.JComboBox<>();
        timeBefore = new javax.swing.JComboBox<>();
        title = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        popup = new javax.swing.JRadioButton();
        email = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        inviter = new javax.swing.JButton();
        event_app = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        event_private = new javax.swing.JRadioButton();
        inviterShow = new javax.swing.JComboBox<>();
        allDay = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        StartDateTimePicker = new com.github.lgooddatepicker.components.DateTimePicker();
        button_Add = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        eventNote = new javax.swing.JTextArea();
        location = new javax.swing.JTextField();
        stateLabel = new javax.swing.JLabel();

        setTitle("編輯事件視窗");

        sms.setText("sms");
        sms.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N

        jLabel8.setText("附件上傳(選)");
        jLabel8.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 20)); // NOI18N

        openFile.setText("Upload");
        openFile.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel9.setText("未新增");
        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N

        jLabel10.setText("可見狀態");
        jLabel10.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 20)); // NOI18N

        watchState.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "default (預設)", "public (活動公開)", "private (只限參與)", "confidential (只限本人)" }));
        watchState.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N

        timeBefore.setEditable(true);
        timeBefore.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10分鐘前", "30分鐘前", "1小時前", "6小時前", "1天前", "1禮拜前" }));
        timeBefore.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N

        title.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        title.setToolTipText("Event name");

        jLabel11.setText("提醒 (簡訊限G Suite用戶)");
        jLabel11.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 20)); // NOI18N

        jLabel1.setText("活動名稱");
        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 20)); // NOI18N

        jLabel2.setText("開始時間");
        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 20)); // NOI18N

        jLabel4.setText("活動類型");
        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 20)); // NOI18N

        popup.setText("popup");
        popup.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N

        email.setText("email");
        email.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N

        jLabel12.setText("與會者(名單)");
        jLabel12.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 20)); // NOI18N

        jLabel3.setText("結束時間");
        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 20)); // NOI18N

        inviter.setText("與會者視窗");
        inviter.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 16)); // NOI18N

        buttonGroup1.add(event_app);
        event_app.setText("共用/公司事件");
        event_app.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N

        jLabel6.setText("活動備註(選)");
        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 20)); // NOI18N

        buttonGroup1.add(event_private);
        event_private.setText("私人事件");
        event_private.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N

        inviterShow.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "尚未新增" }));
        inviterShow.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N

        allDay.setText("全天");
        allDay.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        allDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allDayActionPerformed(evt);
            }
        });

        jLabel7.setText("活動地點(選)");
        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 20)); // NOI18N

        button_Add.setText("新增事件");
        button_Add.setBackground(new java.awt.Color(204, 204, 255));
        button_Add.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N

        eventNote.setColumns(20);
        eventNote.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        eventNote.setRows(5);
        eventNote.setToolTipText("");
        jScrollPane1.setViewportView(eventNote);

        location.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        location.setToolTipText("Event location");

        stateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stateLabel.setText(" ");
        stateLabel.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(watchState, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(inviter, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(event_private)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(event_app))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(allDay)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(StartDateTimePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(EndDateTimePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(31, 31, 31))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(email)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(popup)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(sms)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(timeBefore, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel12)
                    .addComponent(inviterShow, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(28, 28, 28)
                                        .addComponent(openFile, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel9))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(28, 28, 28)
                                        .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(button_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(15, 15, 15)))
                            .addComponent(jLabel6))
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(stateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(openFile, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8))
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(41, 41, 41)
                        .addComponent(button_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(event_app)
                            .addComponent(event_private))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(StartDateTimePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(allDay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(EndDateTimePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(timeBefore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email)
                            .addComponent(popup)
                            .addComponent(sms))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(watchState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inviter, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inviterShow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stateLabel))))
                .addGap(73, 73, 73))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void allDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allDayActionPerformed
        // TODO add your handling code here:
switchAllDay();
    }//GEN-LAST:event_allDayActionPerformed


    
    public void switchAllDay(){
                if(allDay.isSelected()){
            EndDateTimePicker.setEnabled(false);
            StartDateTimePicker.timePicker.setEnabled(false);
        }else{
            EndDateTimePicker.setEnabled(true);
             StartDateTimePicker.timePicker.setEnabled(true);
        }
    }
    
    public JPanel getPanel(){
        return jPanel1;
                
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventEditShow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventEditShow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventEditShow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventEditShow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EventEditShow().setVisible(true);
            }
        });
    }

    public void msgbox(String msg){
        JOptionPane.showMessageDialog(null,msg );
    }
    
    public DateTimePicker getEndDateTimePicker() {
        return EndDateTimePicker;
    }

    public DateTimePicker getStartDateTimePicker() {
        return StartDateTimePicker;
    }

    public JCheckBox getAllDay() {
        return allDay;
    }

    public ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    public JButton getButton_Add() {
        return button_Add;
    }

    public JRadioButton getEmail() {
        return email;
    }

    public JTextArea getEventNote() {
        return eventNote;
    }

    public JRadioButton getEvent_app() {
        return event_app;
    }

    public JRadioButton getEvent_private() {
        return event_private;
    }

    public JButton getInviter() {
        return inviter;
    }

    public JComboBox<String> getInviterShow() {
        return inviterShow;
    }

    public JTextField getLocationText() {
        return location;
    }

    public JButton getOpenFile() {
        return openFile;
    }

    public JRadioButton getPopup() {
        return popup;
    }

    public JRadioButton getSms() {
        return sms;
    }

    public JComboBox<String> getTimeBefore() {
        return timeBefore;
    }

    public JTextField getTitleText() {
        return title;
    }

    public JComboBox<String> getWatchState() {
        return watchState;
    }

    public JLabel getStateLabel() {
        return stateLabel;
    }

   public void setMyData( ArrayList<String> attendess){
        
        inviterShow.setModel(new DefaultComboBoxModel(attendess.toArray()));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.github.lgooddatepicker.components.DateTimePicker EndDateTimePicker;
    private com.github.lgooddatepicker.components.DateTimePicker StartDateTimePicker;
    private javax.swing.JCheckBox allDay;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton button_Add;
    private javax.swing.JRadioButton email;
    private javax.swing.JTextArea eventNote;
    private javax.swing.JRadioButton event_app;
    private javax.swing.JRadioButton event_private;
    private javax.swing.JButton inviter;
    private javax.swing.JComboBox<String> inviterShow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField location;
    private javax.swing.JButton openFile;
    private javax.swing.JRadioButton popup;
    private javax.swing.JRadioButton sms;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JComboBox<String> timeBefore;
    private javax.swing.JTextField title;
    private javax.swing.JComboBox<String> watchState;
    // End of variables declaration//GEN-END:variables
}
