/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyAttendees;

import MyCalendar.CalendarController;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author shane
 */
public class AttendessChooser extends javax.swing.JFrame {

    ArrayList<String> inputData = new  ArrayList<String>();
    ListenForjList jListHandler = new ListenForjList();

    private int focusList = 0;

    ResultSet rs = null;
    int numRows = 0;

    DBconnct conn = new DBconnct();

    /**
     * Creates new form AttendessChooser
     */
    public AttendessChooser() {
        initComponents();

        jList1.addListSelectionListener(jListHandler);
        setComboList(conn.getGroupList());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jTextField_username = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField_email = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField_phone = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField_keyword = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jButton_searchStu = new javax.swing.JButton();
        btnNext1 = new javax.swing.JButton();
        jTextFieldRecNo1 = new javax.swing.JTextField();
        btnPrevious1 = new javax.swing.JButton();
        jButton_searchStu1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        other_email = new javax.swing.JTextField();
        email_but = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setTitle("與會者選擇器");

        jLabel1.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        jLabel1.setText("選擇群組");

        jLabel2.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        jLabel2.setText("新增列表");

        jList1.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "尚未新增" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jComboBox1.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        jButton1.setText("插入");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        jLabel16.setText("使用者名稱");

        jTextField_username.setEditable(false);

        jLabel15.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        jLabel15.setText("電子郵件");

        jTextField_email.setEditable(false);

        jLabel18.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        jLabel18.setText("連絡電話");

        jTextField_phone.setEditable(false);

        jTextField_keyword.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N

        jLabel17.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        jLabel17.setText("搜尋");

        jButton_searchStu.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        jButton_searchStu.setText("確定");
        jButton_searchStu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_searchStuActionPerformed(evt);
            }
        });

        btnNext1.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        btnNext1.setText("Next");
        btnNext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext1ActionPerformed(evt);
            }
        });

        jTextFieldRecNo1.setEditable(false);
        jTextFieldRecNo1.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        jTextFieldRecNo1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnPrevious1.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        btnPrevious1.setText("Previous");
        btnPrevious1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevious1ActionPerformed(evt);
            }
        });

        jButton_searchStu1.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        jButton_searchStu1.setText("顯示全部");
        jButton_searchStu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_searchStu1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        jButton3.setText("插入");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        jLabel19.setText("自訂信箱");

        other_email.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        email_but.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        email_but.setText("插入");
        email_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_butActionPerformed(evt);
            }
        });

        jComboBox2.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton2.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        jButton2.setText("確定選擇");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        jButton4.setText("刪除選中");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(jLabel19)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(other_email, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(email_but, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_keyword, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_searchStu, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel18))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jButton_searchStu1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField_email, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnPrevious1)
                                .addGap(13, 13, 13)
                                .addComponent(jTextFieldRecNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnNext1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(34, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(other_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(email_but, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jTextField_keyword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_searchStu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(jTextField_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(jTextField_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_searchStu1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNext1)
                            .addComponent(btnPrevious1)
                            .addComponent(jTextFieldRecNo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_searchStuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_searchStuActionPerformed

        String chooseW = jComboBox2.getItemAt(jComboBox2.getSelectedIndex());
        String tmpW = jTextField_keyword.getText();
        boolean run = false;
        
        if(!tmpW.equals("")){

        try {
            if (jComboBox2.getSelectedIndex() == 0) {
                if(conn.getSearchUser(tmpW)!=null){
                rs = conn.getSearchUser(tmpW);
                run = true;
                }
            } else {
                if(conn.getSearchKindUser(chooseW, tmpW)!=null){
                rs = conn.getSearchKindUser(chooseW, tmpW);
                run = true;
                }
            }
           
            if (run) {
                rs.last();
                numRows = rs.getRow();
                rs.first();
                showRecord();
            } else {
                JOptionPane.showMessageDialog(rootPane, "查無資料!");
                rs = conn.getSearchUser();
                rs.last();
                numRows = rs.getRow();
                rs.first();
                showRecord();
            
            }
        } catch (SQLException ex) {
            System.out.println("資料庫操作出問題:" + ex.toString());
        }
        
        }else{
             JOptionPane.showMessageDialog(rootPane, "請輸入搜尋內容!");
        }
    }//GEN-LAST:event_jButton_searchStuActionPerformed

    private void btnNext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext1ActionPerformed
     try {
            if (rs.next()) {  //rsult.next()會把紀錄指標指到下一筆紀錄 若成功 則回傳true否則回傳false
                showRecord();
            } else {
                rs.first();
                showRecord();
            }
        } catch (SQLException ex) {
            System.out.println("資料庫操作出問題:" + ex.toString());
        }
    }//GEN-LAST:event_btnNext1ActionPerformed

    private void btnPrevious1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevious1ActionPerformed
   try {
            if (rs.previous()) {
                showRecord();
            } else {
                rs.last();
                showRecord();
            }
        } catch (SQLException ex) {
            System.out.println("資料庫操作出問題:" + ex.toString());
        }
    }//GEN-LAST:event_btnPrevious1ActionPerformed

    private void jButton_searchStu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_searchStu1ActionPerformed
        // TODO add your handling code here:

        String chooseW = jComboBox2.getItemAt(jComboBox2.getSelectedIndex());

        try {

            if (jComboBox2.getSelectedIndex() == 0) {
                 if(conn.getSearchUser()!=null){
                rs = conn.getSearchUser();
                 }
            } else {
                  if(conn.getSearchKindUser(chooseW)!=null){
                rs = conn.getSearchKindUser(chooseW);
                  }
            }

            if (rs.next()) {
                rs.last();
                numRows = rs.getRow();
                rs.first();
                showRecord();
            } else {
                JOptionPane.showMessageDialog(rootPane, "查無資料!");
            }

        } catch (SQLException ex) {
            System.out.println("資料庫操作出問題:" + ex.toString());
        }
    }//GEN-LAST:event_jButton_searchStu1ActionPerformed

    private void showRecord() throws SQLException {
        jTextField_username.setText(rs.getString("u_Name"));
        jTextField_email.setText(rs.getString("u_Email"));
        jTextField_phone.setText(rs.getString("u_Phone"));
        String msg = String.format("第%d / %d筆", rs.getRow(), numRows);
        jTextFieldRecNo1.setText(msg);
    }

    private void email_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_butActionPerformed
        // TODO add your handling code here:
        String tmpMail = "";
        tmpMail = other_email.getText();

        if (isValidEmail(tmpMail)) {
            tmpMail += ",(自訂)";
            inputData.add(tmpMail);
            setList(inputData);
        } else {
            other_email.setText("檢查格式! " + tmpMail);
        }

    }//GEN-LAST:event_email_butActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        inputData.remove(focusList);
        setList(inputData);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ArrayList<String> listUser = new ArrayList<String>();
        listUser.addAll(conn.getGroupUser(jComboBox1.getItemAt(jComboBox1.getSelectedIndex())));

        if (!listUser.isEmpty()) {
            for (int i = 0; i < listUser.size(); i++) {
                String tmpW = listUser.get(i);
                String[] splitW = tmpW.split(",");
                tmpW = splitW[0] + ",(G:" + splitW[1] + ")";
                inputData.add(tmpW);
            }
            setList(inputData);
        } else {
            JOptionPane.showMessageDialog(JOptionPane.getRootFrame(), "本群組無任何綁定使用者");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        String username = jTextField_username.getText();
        String email = jTextField_email.getText();
        String tmpW = "";
        
        tmpW = email + ",(U:" + username + ")";
                inputData.add(tmpW);
            setList(inputData);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton2ActionPerformed

    public JPanel getPanel (){
        return jPanel1;
    }
    
    public static final Pattern EMAIL_PATTERN = Pattern
            .compile("^\\w+\\.*\\w+@(\\w+\\.){1,5}[a-zA-Z]{2,3}$");

    public static boolean isValidEmail(String email) {
        boolean result = false;
        if (EMAIL_PATTERN.matcher(email).matches()) {
            result = true;
        }
        return result;
    }

    
    
    public void setComboList(ArrayList<String> lists) {
        jComboBox1.setModel(new DefaultComboBoxModel(lists.toArray()));
        lists.add(0, "All Group");
        jComboBox2.setModel(new DefaultComboBoxModel(lists.toArray()));
    }

    public void setList(ArrayList<String> lists) {
        jList1.setModel(new javax.swing.AbstractListModel<String>() {

            public int getSize() {
                return lists.size();
            }

            public String getElementAt(int i) {
                return lists.get(i);
            }
        });
    }

    private class ListenForjList implements ListSelectionListener {

        @Override
        public void valueChanged(ListSelectionEvent e) {

            if (jList1.getSelectedIndex() >= 0) {
                focusList = jList1.getSelectedIndex();
            }

        }

    }

    public  ArrayList<String> getAttList(){
        return inputData;
    }
    
        public  void setAttList(ArrayList<String> attList){
            inputData.clear();          
         inputData = attList;
         setList(inputData);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AttendessChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AttendessChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AttendessChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AttendessChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AttendessChooser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext1;
    private javax.swing.JButton btnPrevious1;
    private javax.swing.JButton email_but;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton_searchStu;
    private javax.swing.JButton jButton_searchStu1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldRecNo1;
    private javax.swing.JTextField jTextField_email;
    private javax.swing.JTextField jTextField_keyword;
    private javax.swing.JTextField jTextField_phone;
    private javax.swing.JTextField jTextField_username;
    private javax.swing.JTextField other_email;
    // End of variables declaration//GEN-END:variables
}
