/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyAttendees;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.table.*;

/**
 *
 * @author shane
 */
public class CollaboratorManagement extends javax.swing.JFrame {

    DBconnct conn;
    Statement sta = null;
    int numRows = 0;
    ResultSet rs = null;
    String error_msg = "";
    int runCol;

    /**
     * Creates new form CollaboratorManagement
     */
    public CollaboratorManagement() {
        initComponents();
        conn = new DBconnct();

        sta = conn.getSta();
        //建立panel監聽兵 以便更新(切換時)
        jTabbedPane1.addChangeListener(new ChangeListener() {

            @Override
            public void stateChanged(ChangeEvent e) {
                //System.out.println("Tab: " + jTabbedPane1.getSelectedIndex());
                if (jTabbedPane1.getSelectedIndex() == 1) {
                    jComboBox2.setModel(new DefaultComboBoxModel(conn.getGroupList2().toArray()));
                } else if (jTabbedPane1.getSelectedIndex() == 2) {
                    jComboBox1.setModel(new DefaultComboBoxModel(conn.getGroupList().toArray()));
                } else if (jTabbedPane1.getSelectedIndex() == 3) {
                    AllType.setModel(new DefaultComboBoxModel(conn.getGroupList().toArray()));
                }

            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        btnUpdate1 = new javax.swing.JButton();
        btnInsert1 = new javax.swing.JButton();
        btnDelete1 = new javax.swing.JButton();
        jButtonBlank = new javax.swing.JButton();
        btnFindAll = new javax.swing.JButton();
        btnFindName = new javax.swing.JButton();
        btnFindId = new javax.swing.JButton();
        tfieldFindName = new javax.swing.JTextField();
        tfieldFindStId = new javax.swing.JTextField();
        jTextField_phone = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField_email = new javax.swing.JTextField();
        jTextField_username = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        btnPrevious2 = new javax.swing.JButton();
        jTextFieldRecNo2 = new javax.swing.JTextField();
        btnNext2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButton_searchStu = new javax.swing.JButton();
        jTextField_username2 = new javax.swing.JTextField();
        jTextField_phone2 = new javax.swing.JTextField();
        btnPrevious1 = new javax.swing.JButton();
        jTextFieldRecNo1 = new javax.swing.JTextField();
        btnNext1 = new javax.swing.JButton();
        btnInsert2 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jButton_searchStu1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField_email2 = new javax.swing.JTextField();
        btnInsert3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        btnUpdate_teacher = new javax.swing.JButton();
        btnInsert_teacher = new javax.swing.JButton();
        btnDelete_teacher = new javax.swing.JButton();
        tfieldNewGroup = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnUpdate_teacher1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        AllSearchButton = new javax.swing.JButton();
        AllSearchBox = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaStClassDisplay = new javax.swing.JTextArea();
        AllShowButton = new javax.swing.JButton();
        TypeSearchBox = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        AllType = new javax.swing.JComboBox<>();
        TypeSearchButton = new javax.swing.JButton();
        TypeSearchShow = new javax.swing.JButton();

        setTitle("與會者管理器");

        btnUpdate1.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        btnUpdate1.setText("更新這一筆");
        btnUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate1ActionPerformed(evt);
            }
        });

        btnInsert1.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        btnInsert1.setText("新增這一筆");
        btnInsert1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsert1ActionPerformed(evt);
            }
        });

        btnDelete1.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        btnDelete1.setText("刪除這一筆");
        btnDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete1ActionPerformed(evt);
            }
        });

        jButtonBlank.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        jButtonBlank.setText("新增空白欄位");
        jButtonBlank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBlankActionPerformed(evt);
            }
        });

        btnFindAll.setFont(new java.awt.Font("微軟正黑體", 0, 24)); // NOI18N
        btnFindAll.setText("瀏覽全部");
        btnFindAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindAllActionPerformed(evt);
            }
        });

        btnFindName.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        btnFindName.setText("搜尋姓名");
        btnFindName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindNameActionPerformed(evt);
            }
        });

        btnFindId.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        btnFindId.setText("搜尋信箱");
        btnFindId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindIdActionPerformed(evt);
            }
        });

        tfieldFindName.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N

        tfieldFindStId.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N

        jTextField_phone.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N

        jLabel19.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        jLabel19.setText("連絡電話");

        jLabel20.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        jLabel20.setText("電子郵件");

        jTextField_email.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N

        jTextField_username.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N

        jLabel21.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        jLabel21.setText("使用者名稱");

        btnPrevious2.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        btnPrevious2.setText("Previous");
        btnPrevious2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevious2ActionPerformed(evt);
            }
        });

        jTextFieldRecNo2.setEditable(false);
        jTextFieldRecNo2.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        jTextFieldRecNo2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnNext2.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        btnNext2.setText("Next");
        btnNext2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext2ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        jLabel11.setText("狀態");

        jLabel22.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        jLabel22.setText("等待操作...");

        jLabel1.setText("no.");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfieldFindStId, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFindId))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfieldFindName, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFindName)))
                .addGap(65, 65, 65)
                .addComponent(btnFindAll, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField_email, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnDelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(86, 86, 86))
                                .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnInsert1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonBlank, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)))))
                .addGap(21, 21, 21))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPrevious2)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldRecNo2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNext2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNext2)
                            .addComponent(btnPrevious2)
                            .addComponent(jTextFieldRecNo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel21)
                                .addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jTextField_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnInsert1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jTextField_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(btnUpdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonBlank, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                            .addComponent(btnDelete1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(41, 41, 41)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFindAll, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfieldFindName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFindName))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfieldFindStId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFindId))))
                .addGap(56, 56, 56))
        );

        jTabbedPane1.addTab("使用者管理", jPanel1);

        jLabel8.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel8.setText("配對群組");

        jButton_searchStu.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        jButton_searchStu.setText("搜尋");
        jButton_searchStu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_searchStuActionPerformed(evt);
            }
        });

        jTextField_username2.setEditable(false);

        jTextField_phone2.setEditable(false);

        btnPrevious1.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        btnPrevious1.setText("Previous");
        btnPrevious1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevious1ActionPerformed(evt);
            }
        });

        jTextFieldRecNo1.setEditable(false);
        jTextFieldRecNo1.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        jTextFieldRecNo1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnNext1.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        btnNext1.setText("Next");
        btnNext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext1ActionPerformed(evt);
            }
        });

        btnInsert2.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        btnInsert2.setText("選擇填入");
        btnInsert2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsert2ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        jLabel12.setText("目前配對清單");

        jLabel15.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        jLabel15.setText("電子郵件");

        jLabel16.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        jLabel16.setText("使用者名稱");

        jComboBox2.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 24)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextField2.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N

        jLabel17.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        jLabel17.setText("搜尋");

        jButton_searchStu1.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        jButton_searchStu1.setText("全部顯示");
        jButton_searchStu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_searchStu1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        jLabel5.setText("狀態");

        jLabel7.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        jLabel7.setText("等待配對...");

        jLabel18.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        jLabel18.setText("連絡電話");

        jTextField_email2.setEditable(false);

        btnInsert3.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        btnInsert3.setText("選擇刪除");
        btnInsert3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsert3ActionPerformed(evt);
            }
        });

        jLabel3.setText("no.");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jList1.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "請進行顯示或搜尋" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator4)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(btnPrevious1)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldRecNo1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnNext1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel18))
                                        .addGap(33, 33, 33)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(jTextField_username2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jTextField_email2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField_phone2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel12))
                                            .addComponent(btnInsert3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 20, Short.MAX_VALUE)))))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(110, 110, 110)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(201, 201, 201))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(112, 112, 112))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(jLabel17)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnInsert2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton_searchStu1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton_searchStu, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(48, 48, 48))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(32, 32, 32)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel16)
                                .addComponent(jTextField_username2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3)
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jTextField_email2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jTextField_phone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_searchStu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton_searchStu1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(btnInsert2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnInsert3)
                                .addGap(37, 37, 37))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNext1)
                            .addComponent(btnPrevious1)
                            .addComponent(jTextFieldRecNo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))))
        );

        jTabbedPane1.addTab("配對群組管理", jPanel5);

        btnUpdate_teacher.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        btnUpdate_teacher.setText("更新這一筆");
        btnUpdate_teacher.setEnabled(false);
        btnUpdate_teacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate_teacherActionPerformed(evt);
            }
        });

        btnInsert_teacher.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        btnInsert_teacher.setText("新增這一筆");
        btnInsert_teacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsert_teacherActionPerformed(evt);
            }
        });

        btnDelete_teacher.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        btnDelete_teacher.setText("刪除這一筆");
        btnDelete_teacher.setEnabled(false);
        btnDelete_teacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete_teacherActionPerformed(evt);
            }
        });

        tfieldNewGroup.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("微軟正黑體", 0, 22)); // NOI18N
        jLabel6.setText("新群組名稱");

        jComboBox1.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 24)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextField1.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 22)); // NOI18N
        jLabel4.setText("編輯區");

        btnUpdate_teacher1.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        btnUpdate_teacher1.setText("選擇");
        btnUpdate_teacher1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate_teacher1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        jLabel9.setText("狀態");

        jLabel10.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        jLabel10.setText("等待操作...");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(btnUpdate_teacher)
                                    .addGap(36, 36, 36)
                                    .addComponent(btnDelete_teacher)))
                            .addGap(103, 103, 103)
                            .addComponent(jLabel9)
                            .addGap(229, 229, 229))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnInsert_teacher)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addComponent(tfieldNewGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(366, 366, 366))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(47, 47, 47)
                            .addComponent(btnUpdate_teacher1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(143, 143, 143))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate_teacher1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete_teacher)
                    .addComponent(btnUpdate_teacher))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfieldNewGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btnInsert_teacher)
                .addGap(35, 35, 35))
        );

        jTabbedPane1.addTab("群組管理", jPanel2);

        AllSearchButton.setBackground(new java.awt.Color(102, 51, 255));
        AllSearchButton.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        AllSearchButton.setText("Search");
        AllSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllSearchButtonActionPerformed(evt);
            }
        });

        AllSearchBox.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N

        txtAreaStClassDisplay.setColumns(20);
        txtAreaStClassDisplay.setRows(5);
        jScrollPane2.setViewportView(txtAreaStClassDisplay);

        AllShowButton.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        AllShowButton.setText("Search/ALL");
        AllShowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllShowButtonActionPerformed(evt);
            }
        });

        TypeSearchBox.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N

        jLabel13.setFont(new java.awt.Font("標楷體", 0, 18)); // NOI18N
        jLabel13.setText("所有分類");

        jLabel14.setFont(new java.awt.Font("標楷體", 0, 18)); // NOI18N
        jLabel14.setText("查詢分類");

        AllType.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        AllType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        TypeSearchButton.setBackground(new java.awt.Color(255, 51, 51));
        TypeSearchButton.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        TypeSearchButton.setText("Search");
        TypeSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeSearchButtonActionPerformed(evt);
            }
        });

        TypeSearchShow.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        TypeSearchShow.setText("Search/ALL");
        TypeSearchShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeSearchShowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(TypeSearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AllType, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(TypeSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TypeSearchShow, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(AllSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(AllShowButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(AllSearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(AllSearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AllSearchButton)
                        .addGap(18, 18, 18)
                        .addComponent(AllShowButton)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AllType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(TypeSearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TypeSearchButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TypeSearchShow))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("查詢與報表", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDelete_teacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete_teacherActionPerformed

        int n = JOptionPane.showConfirmDialog(null, "確認刪除?(此動作將遺失所有關聯)", "刪除確認", JOptionPane.YES_NO_OPTION);

        if (n == JOptionPane.YES_OPTION) {
            String oldText = jComboBox1.getItemAt(jComboBox1.getSelectedIndex());

            String sql = String.format("DELETE FROM group_list\n"
                    + "WHERE g_Name =  '%s'", oldText);
            System.out.println(sql);

            try {
                rs = sta.executeQuery(sql);
                jLabel10.setText("刪除成功!");
                jComboBox1.setModel(new DefaultComboBoxModel(conn.getGroupList().toArray()));
                btnUpdate_teacher.setEnabled(false);
                btnDelete_teacher.setEnabled(false);
            } catch (SQLException ex) {
                System.out.println("資料庫操作出問題:" + ex.toString());
            }
        }
    }//GEN-LAST:event_btnDelete_teacherActionPerformed

    private void btnInsert_teacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsert_teacherActionPerformed

        String groupText = tfieldNewGroup.getText();
        if (!groupText.equals("")) {

            String sql = String.format("INSERT INTO group_list (g_Name)\n"
                    + "VALUES ('%s')", groupText);
            System.out.println(sql);

            try {
                rs = sta.executeQuery(sql);
                jLabel10.setText("新增成功!");
                jComboBox1.setModel(new DefaultComboBoxModel(conn.getGroupList().toArray()));
            } catch (SQLException ex) {
                System.out.println("資料庫操作出問題:" + ex.toString());
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "請輸入內容!");
        }
    }//GEN-LAST:event_btnInsert_teacherActionPerformed

    private void btnUpdate_teacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate_teacherActionPerformed
        // TODO add your handling code here:
        String oldText = jComboBox1.getItemAt(jComboBox1.getSelectedIndex());
        String updateText = jTextField1.getText();

        String sql = String.format("UPDATE group_list\n"
                + "SET g_Name = '%s'\n"
                + "WHERE g_Name =  '%s'", updateText, oldText);
        System.out.println(sql);

        try {
            rs = sta.executeQuery(sql);
            jLabel10.setText("更新成功!");
            jComboBox1.setModel(new DefaultComboBoxModel(conn.getGroupList().toArray()));
            btnUpdate_teacher.setEnabled(false);
            btnDelete_teacher.setEnabled(false);
        } catch (SQLException ex) {
            System.out.println("資料庫操作出問題:" + ex.toString());
        }

    }//GEN-LAST:event_btnUpdate_teacherActionPerformed

    private void btnInsert2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsert2ActionPerformed
 
        try{
            
            String select = jComboBox2.getItemAt(jComboBox2.getSelectedIndex());
            String [] splitW = select.split(",");
            
            
        String sql = String.format("Insert into advisor_usergroup (a_Uid,a_Gid) "
                        + "values ('%s','%s')",
                        jLabel23.getText(), splitW[0]);

        runCol = rs.getRow();
        
                 sta.execute(sql);
            jLabel7.setText("新增成功!");
            rs = sta.executeQuery("select * from user_list");
            rs.relative(runCol); //定位到目前位置
            showRecord2();
  
        } catch (SQLException e) {
            System.out.println("資料庫操作出問題:" + e.toString());
        }
        
    }//GEN-LAST:event_btnInsert2ActionPerformed

    private void btnNext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext1ActionPerformed
        try {
            if (rs.next()) {  //rsult.next()會把紀錄指標指到下一筆紀錄 若成功 則回傳true否則回傳false
                showRecord2();
            } else {
                rs.first();
                showRecord2();
            }
        } catch (SQLException ex) {
            System.out.println("資料庫操作出問題:" + ex.toString());
        }
    }//GEN-LAST:event_btnNext1ActionPerformed

    private void btnPrevious1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevious1ActionPerformed
        try {
            if (rs.previous()) {
                showRecord2();
            } else {
                rs.last();
                showRecord2();
            }
        } catch (SQLException ex) {
            System.out.println("資料庫操作出問題:" + ex.toString());
        }
    }//GEN-LAST:event_btnPrevious1ActionPerformed

    private void jButton_searchStuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_searchStuActionPerformed
  
        String tmpW = jTextField2.getText();
        
        if (!tmpW.equals("")) {
            
        String sql = String.format("SELECT *\n"
                + "FROM user_list\n"
          + "WHERE u_Name LIKE '%%%s%%' OR u_Email LIKE '%%%s%%' OR u_Phone LIKE '%%%s%%'",tmpW,tmpW,tmpW);
        System.out.println(sql);

        try {
            rs = sta.executeQuery(sql);

            if (rs.next()) {
                rs.last();
                numRows = rs.getRow();
                rs.first();
                showRecord2();
            } else {
                JOptionPane.showMessageDialog(rootPane, "查無資料!");
            }

        } catch (SQLException ex) {
            System.out.println("資料庫操作出問題:" + ex.toString());
        }
             } else {
            JOptionPane.showMessageDialog(rootPane, "請輸入搜尋內容!");
        }
    }//GEN-LAST:event_jButton_searchStuActionPerformed

    private void btnFindIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindIdActionPerformed
        String sql = String.format("select * from user_list where u_Email like '%s%s%s' ", "%", tfieldFindStId.getText(), "%");

        try {
            rs = sta.executeQuery(sql);
            if (rs.next()) {
                rs.last();
                numRows = rs.getRow();
                rs.first();
                showRecord();
            } else {
                JOptionPane.showMessageDialog(rootPane, "查無資料!");
                rs = sta.executeQuery("select * from user_list");
                rs.last();
                numRows = rs.getRow();
                rs.first();
                showRecord();
            }

        } catch (SQLException ex) {
            System.out.println("資料庫操作出問題:" + ex.toString());
        }
    }//GEN-LAST:event_btnFindIdActionPerformed

    private void btnFindNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindNameActionPerformed
        String sql = String.format("select * from user_list where u_Name like '%s%s%s' ", "%", tfieldFindName.getText(), "%");

        try {
            rs = sta.executeQuery(sql);
            if (rs.next()) {
                rs.last();
                numRows = rs.getRow();
                rs.first();
                showRecord();
            } else {
                JOptionPane.showMessageDialog(rootPane, "查無資料!");
                rs = sta.executeQuery("select * from user_list");
                rs.last();
                numRows = rs.getRow();
                rs.first();
                showRecord();
            }

        } catch (SQLException ex) {
            System.out.println("資料庫操作出問題:" + ex.toString());
        }
    }//GEN-LAST:event_btnFindNameActionPerformed

    private void btnFindAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindAllActionPerformed

        String sql = String.format("SELECT *\n"
                + "FROM user_list");
        System.out.println(sql);

        try {
            rs = sta.executeQuery(sql);

            if (rs.next()) {
                rs.last();
                numRows = rs.getRow();
                rs.first();
                showRecord();
            } else {
                JOptionPane.showMessageDialog(rootPane, "查無資料!");
            }

        } catch (SQLException ex) {
            System.out.println("資料庫操作出問題:" + ex.toString());
        }
    }//GEN-LAST:event_btnFindAllActionPerformed

    private void showRecord() throws SQLException {
        jTextField_username.setText(rs.getString("u_Name"));
        jTextField_email.setText(rs.getString("u_Email"));
        jTextField_phone.setText(rs.getString("u_Phone"));
        jLabel2.setText(rs.getString("u_Id"));
        runCol = rs.getRow();
        String msg = String.format("第%d / %d筆", rs.getRow(), numRows);
        jTextFieldRecNo2.setText(msg);
    }

    private void showRecord2() throws SQLException {
        jTextField_username2.setText(rs.getString("u_Name"));
        jTextField_email2.setText(rs.getString("u_Email"));
        jTextField_phone2.setText(rs.getString("u_Phone"));
        jLabel23.setText(rs.getString("u_Id"));
        String msg = String.format("第%d / %d筆", rs.getRow(), numRows);
        jTextFieldRecNo1.setText(msg);

        runHavaGroup(jLabel23.getText());
    }

    private void runHavaGroup(String uid) throws SQLException {
        ResultSet rs3 = null;
        String sql = String.format("SELECT *\n"
                + "FROM user_list\n"
                + "INNER JOIN advisor_usergroup on advisor_usergroup.a_Uid = user_list.u_Id\n"
                + "INNER JOIN group_list ON group_list.g_Id = advisor_usergroup.a_Gid\n"
                + "WHERE user_list.u_Id= '%s'", uid);
        System.out.println(sql);

        jList1.removeAll();

        try {
            rs3 = sta.executeQuery(sql);
            ArrayList<String> myList = new ArrayList<String>();

            if (rs3.next() == false) {

            } else {

                do { //開始輸出
                    myList.add(rs3.getString("g_Id")+","+rs3.getString("g_Name"));
                } while (rs3.next());

                //System.out.println(msg);
            }
            setList(myList);
        } catch (SQLException ex) {
            System.out.println("資料庫操作出問題:" + ex.toString());
        }
    }

    public void setList(ArrayList<String> lists) {
        jList1.setModel(new javax.swing.AbstractListModel<String>() {

            public int getSize() {
                return lists.size();
            }

            public String getElementAt(int i) {
                return lists.get(i);
            }
        });
    }

    private void jButtonBlankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBlankActionPerformed
        jTextField_username.setText("");
        jTextField_email.setText("");
        jTextField_phone.setText("");

        String msg = String.format("%d/%d", numRows + 1, numRows);
        jTextFieldRecNo2.setText(msg);
    }//GEN-LAST:event_jButtonBlankActionPerformed

    private void btnDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete1ActionPerformed
        String sql = String.format("Delete from user_list where u_Email='%s'",
                jTextField_email.getText());

        try {

            int opt = JOptionPane.showConfirmDialog(this, String.format("請問是否確定刪除使用者「%s」", rs.getString("u_Name")), "確認",
                    JOptionPane.OK_CANCEL_OPTION,
                    JOptionPane.INFORMATION_MESSAGE);

            if (opt == 0) {

                sta.execute(sql);
                jLabel22.setText("刪除成功!");
                rs = sta.executeQuery("select * from student");
                rs.last();
                numRows = rs.getRow();
                rs.first();
                showRecord();
            } else {
                jLabel22.setText("取消操作");
            }

        } catch (SQLException e) {
            System.out.println("資料庫操作出問題:" + e.toString());
        }
    }//GEN-LAST:event_btnDelete1ActionPerformed

    private void btnInsert1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsert1ActionPerformed

        try {
            String sql = String.format("Insert into user_list (u_Name,u_Email,u_Phone) "
                    + "values ('%s','%s','%s')",
                    jTextField_username.getText(),
                    jTextField_email.getText(),
                    jTextField_phone.getText());

            sta.execute(sql);
            jLabel22.setText("新增成功!");
            rs = sta.executeQuery("select * from user_list");
            rs.last();
            numRows = rs.getRow();
            showRecord();

        } catch (SQLException e) {
            System.out.println("資料庫操作出問題:" + e.toString());
        }
    }//GEN-LAST:event_btnInsert1ActionPerformed

    private void btnUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate1ActionPerformed

        try {
            String sql = String.format("update user_list set u_Name='%s',u_Email='%s',u_Phone='%s' where u_Id='%s'",
                    jTextField_username.getText(),
                    jTextField_email.getText(),
                    jTextField_phone.getText(),
                    jLabel2.getText());

            sta.execute(sql);
            jLabel22.setText("更新成功!");
            rs = sta.executeQuery("select * from user_list");
            rs.last();
            numRows = rs.getRow();
            rs.relative(runCol); //定位到目前位置
            showRecord();

        } catch (SQLException e) {
            System.out.println("資料庫操作出問題:" + e.toString());
        }
    }//GEN-LAST:event_btnUpdate1ActionPerformed

    private void AllShowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllShowButtonActionPerformed

        String sql = String.format("SELECT user_list.*,group_list.g_Name\n"
                + "FROM user_list \n"
                + "INNER JOIN advisor_usergroup on advisor_usergroup.a_Uid = user_list.u_Id\n"
                + "INNER JOIN group_list ON group_list.g_Id = advisor_usergroup.a_Gid");
        System.out.println(sql);
        txtAreaStClassDisplay.setText("");
        String msg;

        try {
            rs = sta.executeQuery(sql);
            if (rs.next() == false) {
                JOptionPane.showMessageDialog(rootPane, "查無資料!");
            } else {
                txtAreaStClassDisplay.append("姓名\t群組\t\tE-mail\n");
                txtAreaStClassDisplay.append("-------------------------------------------------------------\n");
                do { //開始輸出課程
                    msg = String.format("%s\t%s\t%s\n", rs.getString("u_Name"), rs.getString("g_Name"), rs.getString("u_Email"));
                    txtAreaStClassDisplay.append(msg);
                } while (rs.next());
                txtAreaStClassDisplay.append("-------------------------------------------------------------\n");

                //System.out.println(msg);
            }
        } catch (SQLException ex) {
            System.out.println("資料庫操作出問題:" + ex.toString());
        }
    }//GEN-LAST:event_AllShowButtonActionPerformed

    private void AllSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllSearchButtonActionPerformed

        String tmpW = AllSearchBox.getText();
        if (!tmpW.equals("")) {
            String sql = String.format("SELECT user_list.*,group_list.g_Name\n"
                    + "FROM user_list \n"
                    + "INNER JOIN advisor_usergroup on advisor_usergroup.a_Uid = user_list.u_Id\n"
                    + "INNER JOIN group_list ON group_list.g_Id = advisor_usergroup.a_Gid\n"
                    + "WHERE u_Name LIKE '%%%s%%' OR u_Email LIKE '%%%s%%' OR u_Phone LIKE '%%%s%%'", tmpW, tmpW, tmpW);
            System.out.println(sql);
            txtAreaStClassDisplay.setText("");
            String msg;

            try {
                rs = sta.executeQuery(sql);
                if (rs.next() == false) {
                    JOptionPane.showMessageDialog(rootPane, "查無資料!");
                } else {
                    txtAreaStClassDisplay.append("姓名\t群組\t\tE-mail\n");
                    txtAreaStClassDisplay.append("-------------------------------------------------------------\n");
                    do { //開始輸出課程
                        msg = String.format("%s\t%s\t%s\n", rs.getString("u_Name"), rs.getString("g_Name"), rs.getString("u_Email"));
                        txtAreaStClassDisplay.append(msg);
                    } while (rs.next());
                    txtAreaStClassDisplay.append("-------------------------------------------------------------\n");

                    //System.out.println(msg);
                }
            } catch (SQLException ex) {
                System.out.println("資料庫操作出問題:" + ex.toString());
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "請輸入搜尋內容!");
        }
    }//GEN-LAST:event_AllSearchButtonActionPerformed

    private void TypeSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeSearchButtonActionPerformed
        // TODO add your handling code here:
        String chooseW = AllType.getItemAt(AllType.getSelectedIndex());
        String tmpW = TypeSearchBox.getText();
        if (!tmpW.equals("")) {
            String sql = String.format("SELECT user_list.*,group_list.g_Name\n"
                    + "FROM user_list \n"
                    + "INNER JOIN advisor_usergroup on advisor_usergroup.a_Uid = user_list.u_Id\n"
                    + "INNER JOIN group_list ON group_list.g_Id = advisor_usergroup.a_Gid\n"
                    + "WHERE (u_Name LIKE '%%%s%%' OR u_Email LIKE '%%%s%%' OR u_Phone LIKE '%%%s%%') AND group_list.g_Name = '%s'", tmpW, tmpW, tmpW, chooseW);
            System.out.println(sql);
            txtAreaStClassDisplay.setText("");
            String msg;

            try {
                rs = sta.executeQuery(sql);
                if (rs.next() == false) {
                    JOptionPane.showMessageDialog(rootPane, "查無資料!");
                } else {
                    txtAreaStClassDisplay.append("姓名\t群組\t\tE-mail\n");
                    txtAreaStClassDisplay.append("-------------------------------------------------------------\n");
                    do { //開始輸出課程
                        msg = String.format("%s\t%s\t%s\n", rs.getString("u_Name"), rs.getString("g_Name"), rs.getString("u_Email"));
                        txtAreaStClassDisplay.append(msg);
                    } while (rs.next());
                    txtAreaStClassDisplay.append("-------------------------------------------------------------\n");

                    //System.out.println(msg);
                }
            } catch (SQLException ex) {
                System.out.println("資料庫操作出問題:" + ex.toString());
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "請輸入搜尋內容!");
        }
    }//GEN-LAST:event_TypeSearchButtonActionPerformed

    private void TypeSearchShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeSearchShowActionPerformed
        // TODO add your handling code here:

        String chooseW = AllType.getItemAt(AllType.getSelectedIndex());

        String sql = String.format("SELECT user_list.*,group_list.g_Name\n"
                + "FROM user_list \n"
                + "INNER JOIN advisor_usergroup on advisor_usergroup.a_Uid = user_list.u_Id\n"
                + "INNER JOIN group_list ON group_list.g_Id = advisor_usergroup.a_Gid\n"
                + "WHERE group_list.g_Name = '%s'", chooseW);
        System.out.println(sql);
        txtAreaStClassDisplay.setText("");
        String msg;

        try {
            rs = sta.executeQuery(sql);
            if (rs.next() == false) {
                JOptionPane.showMessageDialog(rootPane, "查無資料!");
            } else {
                txtAreaStClassDisplay.append("姓名\t群組\t\tE-mail\n");
                txtAreaStClassDisplay.append("-------------------------------------------------------------\n");
                do { //開始輸出課程
                    msg = String.format("%s\t%s\t%s\n", rs.getString("u_Name"), rs.getString("g_Name"), rs.getString("u_Email"));
                    txtAreaStClassDisplay.append(msg);
                } while (rs.next());
                txtAreaStClassDisplay.append("-------------------------------------------------------------\n");

                //System.out.println(msg);
            }
        } catch (SQLException ex) {
            System.out.println("資料庫操作出問題:" + ex.toString());
        }
    }//GEN-LAST:event_TypeSearchShowActionPerformed

    private void jButton_searchStu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_searchStu1ActionPerformed
        // TODO add your handling code here:
        String sql = String.format("SELECT *\n"
                + "FROM user_list");
        System.out.println(sql);

        try {
            rs = sta.executeQuery(sql);

            if (rs.next()) {
                rs.last();
                numRows = rs.getRow();
                rs.first();
                showRecord2();
            } else {
                JOptionPane.showMessageDialog(rootPane, "查無資料!");
            }

        } catch (SQLException ex) {
            System.out.println("資料庫操作出問題:" + ex.toString());
        }
    }//GEN-LAST:event_jButton_searchStu1ActionPerformed

    private void btnPrevious2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevious2ActionPerformed
        // TODO add your handling code here:
        try {
            if (rs.previous()) {
                showRecord();
            } else {
                rs.last();
                showRecord();
            }
        } catch (SQLException ex) {
            System.out.println("資料庫操作出問題:" + ex.toString());
        }
    }//GEN-LAST:event_btnPrevious2ActionPerformed

    private void btnNext2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext2ActionPerformed
        // TODO add your handling code here:
        try {
            if (rs.next()) {  //rsult.next()會把紀錄指標指到下一筆紀錄 若成功 則回傳true否則回傳false
                showRecord();
            } else {
                rs.first();
                showRecord();
            }
        } catch (SQLException ex) {
            System.out.println("資料庫操作出問題:" + ex.toString());
        }
    }//GEN-LAST:event_btnNext2ActionPerformed

    private void btnUpdate_teacher1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate_teacher1ActionPerformed
        // TODO add your handling code here:
        jLabel10.setText("等待編輯...");
        btnUpdate_teacher.setEnabled(true);
        btnDelete_teacher.setEnabled(true);
        jTextField1.setText(jComboBox1.getItemAt(jComboBox1.getSelectedIndex()));
    }//GEN-LAST:event_btnUpdate_teacher1ActionPerformed

    private void btnInsert3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsert3ActionPerformed
        // TODO add your handling code here:
ResultSet rs2 = null;
        String selectW = jList1.getSelectedValue();
        int n = JOptionPane.showConfirmDialog(null, "確認刪除 " + selectW + " ?(此動作將遺失所有關聯)", "刪除確認", JOptionPane.YES_NO_OPTION);

        if (n == JOptionPane.YES_OPTION) {

            try {

                String [] splitW = selectW.split(",");
                
               String  sql = String.format("DELETE FROM advisor_usergroup\n"
                        + "WHERE a_Uid =  '%s' AND a_Gid =  '%s' ", jLabel23.getText(), splitW[0]);
                System.out.println(sql);

                rs2 = sta.executeQuery(sql);
                jLabel7.setText("刪除成功!");
                
                runHavaGroup(jLabel23.getText());
            } catch (SQLException ex) {
                System.out.println("資料庫操作出問題:" + ex.toString());
            }
        }

    }//GEN-LAST:event_btnInsert3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CollaboratorManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CollaboratorManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CollaboratorManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CollaboratorManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CollaboratorManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AllSearchBox;
    private javax.swing.JButton AllSearchButton;
    private javax.swing.JButton AllShowButton;
    private javax.swing.JComboBox<String> AllType;
    private javax.swing.JTextField TypeSearchBox;
    private javax.swing.JButton TypeSearchButton;
    private javax.swing.JButton TypeSearchShow;
    private javax.swing.JButton btnDelete1;
    private javax.swing.JButton btnDelete_teacher;
    private javax.swing.JButton btnFindAll;
    private javax.swing.JButton btnFindId;
    private javax.swing.JButton btnFindName;
    private javax.swing.JButton btnInsert1;
    private javax.swing.JButton btnInsert2;
    private javax.swing.JButton btnInsert3;
    private javax.swing.JButton btnInsert_teacher;
    private javax.swing.JButton btnNext1;
    private javax.swing.JButton btnNext2;
    private javax.swing.JButton btnPrevious1;
    private javax.swing.JButton btnPrevious2;
    private javax.swing.JButton btnUpdate1;
    private javax.swing.JButton btnUpdate_teacher;
    private javax.swing.JButton btnUpdate_teacher1;
    private javax.swing.JButton jButtonBlank;
    private javax.swing.JButton jButton_searchStu;
    private javax.swing.JButton jButton_searchStu1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextFieldRecNo1;
    private javax.swing.JTextField jTextFieldRecNo2;
    private javax.swing.JTextField jTextField_email;
    private javax.swing.JTextField jTextField_email2;
    private javax.swing.JTextField jTextField_phone;
    private javax.swing.JTextField jTextField_phone2;
    private javax.swing.JTextField jTextField_username;
    private javax.swing.JTextField jTextField_username2;
    private javax.swing.JTextField tfieldFindName;
    private javax.swing.JTextField tfieldFindStId;
    private javax.swing.JTextField tfieldNewGroup;
    private javax.swing.JTextArea txtAreaStClassDisplay;
    // End of variables declaration//GEN-END:variables
}
